@startuml
queue kafka

control Service_расчета_стоимости_зуба
database calc_DB

autonumber

Service_расчета_стоимости_зуба->kafka: получаем событие из топика
Service_расчета_стоимости_зуба->calc_DB: получаем текущие данные о зубе и его болезнях
Service_расчета_стоимости_зуба-> Service_расчета_стоимости_зуба: применяем новое состояние на нашу сущность
Service_расчета_стоимости_зуба->Service_расчета_стоимости_зуба: рассчитываем стоимость зуба
Service_расчета_стоимости_зуба->calc_DB: сохраняем в БД
Service_расчета_стоимости_зуба->kafka: публикуем событие об изменении стоимости зуба

@enduml