@startuml
actor Фея
actor Ребенок

boundary UI
note over UI: опускаем наличие Gateway
control Service_Сделка
control Service_Счет
boundary Service_расчета_стоимости_зуба

autonumber

Фея->UI: Создать сделку с конкретным ребенком
UI->Service_Сделка: Создать сделку с конкретным ребенком
Service_Сделка->Service_Сделка: Создание сделки
Service_Сделка-->UI: сделка создана
UI-->Фея: сделка создана

loop [есть не осмотренные молочные зубы]
    Фея->Ребенок: Забрать зуб
    Фея->UI: Забрать конкретный зуб
    UI->Service_Сделка: создать item сделки по конкретному зубу в БД
    Service_Сделка->Service_расчета_стоимости_зуба: получить стоимость зуба
    Service_Сделка->Service_Сделка: создать item сделки по конкретному зубу в БД в статусе PENDING_RESERVED
    Service_Сделка->Service_Счет: Зарезервировать сумму под новый зуб на счете у опр феи
    Service_Счет->Service_Счет: Резерв новой суммы  на счете у опр феи
    Service_Счет-->Service_Сделка: зарезервировано
    Service_Сделка->Service_Сделка: Певести статус итема в RESERVED
    Service_Сделка->UI: зуб зарезервирован
    UI->Фея: зуб зарезервирован
    
end 

Фея->UI: завершить сделку
UI->Service_Сделка: завершить сделку
Service_Сделка->Service_Счет: Спиши сумму по опр сделке и зачисли на счет опр ребенку
Service_Счет->Service_Счет: списываем деньги у феи и зачисляем их ребенку
Service_Счет-->Service_Сделка: транзакция произведена
Service_Сделка->Service_Сделка: Перевести сделку в статус COMPLETED
Service_Сделка-->UI: сделка проведена
UI-->Фея: сделка проведена

@enduml